spring:
  # datasource 数据源配置内容
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/testb5f4?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&allowMultiQueries=true}
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
  # JPA 配置内容，对应 JpaProperties 类
  jpa:
    show-sql: true # 打印 SQL 。生产环境，建议关闭
    database-platform: org.hibernate.dialect.MySQL5Dialect
    # Hibernate 配置内容，对应 HibernateProperties 类
    hibernate:
      ddl-auto: none